/* Generated by Yosys 0.57+157 (git sha1 b9dc57841, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/harsh-shah/week1/Day4/bad_mux.v:1.1-8.10" *)
module bad_mux(i0, i1, sel, y);
  (* src = "/home/harsh-shah/week1/Day4/bad_mux.v:1.23-1.25" *)
  input i0;
  wire i0;
  (* src = "/home/harsh-shah/week1/Day4/bad_mux.v:1.33-1.35" *)
  input i1;
  wire i1;
  (* src = "/home/harsh-shah/week1/Day4/bad_mux.v:1.43-1.46" *)
  input sel;
  wire sel;
  (* src = "/home/harsh-shah/week1/Day4/bad_mux.v:1.59-1.60" *)
  output y;
  wire y;
  (* src = "/home/harsh-shah/week1/Day4/bad_mux.v:1.23-1.25" *)
  wire \$abc$85$i0 ;
  (* src = "/home/harsh-shah/week1/Day4/bad_mux.v:1.33-1.35" *)
  wire \$abc$85$i1 ;
  (* src = "/home/harsh-shah/week1/Day4/bad_mux.v:1.43-1.46" *)
  wire \$abc$85$sel ;
  (* src = "/home/harsh-shah/week1/Day4/bad_mux.v:1.59-1.60" *)
  wire \$abc$85$y ;
  sky130_fd_sc_hd__mux2_1 \$abc$85$auto$blifparse.cc:397:parse_blif$86  (
    .A0(\$abc$85$i0 ),
    .A1(\$abc$85$i1 ),
    .S(\$abc$85$sel ),
    .X(\$abc$85$y )
  );
  assign \$abc$85$i0  = i0;
  assign \$abc$85$i1  = i1;
  assign \$abc$85$sel  = sel;
  assign y = \$abc$85$y ;
endmodule
