/* Generated by Yosys 0.57+157 (git sha1 b9dc57841, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/harsh-shah/week1/Day4/mux.v:1.1-3.10" *)
module mux(i0, i1, sel, y);
  (* src = "/home/harsh-shah/week1/Day4/mux.v:1.19-1.21" *)
  input i0;
  wire i0;
  (* src = "/home/harsh-shah/week1/Day4/mux.v:1.29-1.31" *)
  input i1;
  wire i1;
  (* src = "/home/harsh-shah/week1/Day4/mux.v:1.39-1.42" *)
  input sel;
  wire sel;
  (* src = "/home/harsh-shah/week1/Day4/mux.v:1.51-1.52" *)
  output y;
  wire y;
  (* src = "/home/harsh-shah/week1/Day4/mux.v:1.19-1.21" *)
  wire \$abc$82$i0 ;
  (* src = "/home/harsh-shah/week1/Day4/mux.v:1.29-1.31" *)
  wire \$abc$82$i1 ;
  (* src = "/home/harsh-shah/week1/Day4/mux.v:1.39-1.42" *)
  wire \$abc$82$sel ;
  (* src = "/home/harsh-shah/week1/Day4/mux.v:1.51-1.52" *)
  wire \$abc$82$y ;
  sky130_fd_sc_hd__mux2_1 \$abc$82$auto$blifparse.cc:397:parse_blif$83  (
    .A0(\$abc$82$i0 ),
    .A1(\$abc$82$i1 ),
    .S(\$abc$82$sel ),
    .X(\$abc$82$y )
  );
  assign \$abc$82$i0  = i0;
  assign \$abc$82$i1  = i1;
  assign \$abc$82$sel  = sel;
  assign y = \$abc$82$y ;
endmodule
