/* Generated by Yosys 0.57+157 (git sha1 b9dc57841, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/harsh-shah/week1/Day3/opt_check2.v:1.1-3.10" *)
module opt_check2(a, b, y);
  (* src = "/home/harsh-shah/week1/Day3/opt_check2.v:1.26-1.27" *)
  input a;
  wire a;
  (* src = "/home/harsh-shah/week1/Day3/opt_check2.v:1.36-1.37" *)
  input b;
  wire b;
  (* src = "/home/harsh-shah/week1/Day3/opt_check2.v:1.47-1.48" *)
  output y;
  wire y;
  (* src = "/home/harsh-shah/week1/Day3/opt_check2.v:1.26-1.27" *)
  wire \$abc$83$a ;
  (* src = "/home/harsh-shah/week1/Day3/opt_check2.v:1.36-1.37" *)
  wire \$abc$83$b ;
  (* src = "/home/harsh-shah/week1/Day3/opt_check2.v:1.47-1.48" *)
  wire \$abc$83$y ;
  sky130_fd_sc_hd__or2_0 \$abc$83$auto$blifparse.cc:397:parse_blif$84  (
    .A(\$abc$83$a ),
    .B(\$abc$83$b ),
    .X(\$abc$83$y )
  );
  assign \$abc$83$a  = a;
  assign \$abc$83$b  = b;
  assign y = \$abc$83$y ;
endmodule
