/* Generated by Yosys 0.57+157 (git sha1 b9dc57841, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/harsh-shah/week1/Day5/bad_case.v:1.1-14.10" *)
module bad_case(i0, i1, i2, i3, sel, y);
  (* src = "/home/harsh-shah/week1/Day5/bad_case.v:2.11-2.13" *)
  input i0;
  wire i0;
  (* src = "/home/harsh-shah/week1/Day5/bad_case.v:2.21-2.23" *)
  input i1;
  wire i1;
  (* src = "/home/harsh-shah/week1/Day5/bad_case.v:2.31-2.33" *)
  input i2;
  wire i2;
  (* src = "/home/harsh-shah/week1/Day5/bad_case.v:2.41-2.43" *)
  input i3;
  wire i3;
  (* src = "/home/harsh-shah/week1/Day5/bad_case.v:3.17-3.20" *)
  input [1:0] sel;
  wire [1:0] sel;
  (* src = "/home/harsh-shah/week1/Day5/bad_case.v:4.16-4.17" *)
  output y;
  wire y;
  wire \$abc$251$new_n10 ;
  wire \$abc$251$new_n11 ;
  wire \$abc$251$new_n12 ;
  wire \$abc$251$new_n13 ;
  wire \$abc$251$new_n14 ;
  wire \$abc$251$new_n15 ;
  wire \$abc$251$new_n16 ;
  wire \$abc$251$new_n8 ;
  wire \$abc$251$new_n9 ;
  (* src = "/home/harsh-shah/week1/Day5/bad_case.v:2.11-2.13" *)
  wire \$abc$262$i0 ;
  (* src = "/home/harsh-shah/week1/Day5/bad_case.v:2.21-2.23" *)
  wire \$abc$262$i1 ;
  (* src = "/home/harsh-shah/week1/Day5/bad_case.v:2.31-2.33" *)
  wire \$abc$262$i2 ;
  (* src = "/home/harsh-shah/week1/Day5/bad_case.v:2.41-2.43" *)
  wire \$abc$262$i3 ;
  (* src = "/home/harsh-shah/week1/Day5/bad_case.v:3.17-3.20" *)
  wire \$abc$262$sel[0] ;
  (* src = "/home/harsh-shah/week1/Day5/bad_case.v:3.17-3.20" *)
  wire \$abc$262$sel[1] ;
  (* src = "/home/harsh-shah/week1/Day5/bad_case.v:4.16-4.17" *)
  wire \$abc$262$y ;
  sky130_fd_sc_hd__mux4_2 \$abc$262$auto$blifparse.cc:397:parse_blif$263  (
    .A0(\$abc$262$i0 ),
    .A1(\$abc$262$i1 ),
    .A2(\$abc$262$i2 ),
    .A3(\$abc$262$i3 ),
    .S0(\$abc$262$sel[0] ),
    .S1(\$abc$262$sel[1] ),
    .X(\$abc$262$y )
  );
  assign \$abc$262$sel[0]  = sel[0];
  assign \$abc$262$sel[1]  = sel[1];
  assign \$abc$262$i2  = i2;
  assign \$abc$262$i1  = i1;
  assign \$abc$262$i0  = i0;
  assign \$abc$262$i3  = i3;
  assign y = \$abc$262$y ;
endmodule
