/* Generated by Yosys 0.57+157 (git sha1 b9dc57841, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/harsh-shah/week1/Day5/comp_case.v:1.1-9.10" *)
module comp_case(i0, i1, i2, sel, y);
  (* src = "/home/harsh-shah/week1/Day5/comp_case.v:1.25-1.27" *)
  input i0;
  wire i0;
  (* src = "/home/harsh-shah/week1/Day5/comp_case.v:1.35-1.37" *)
  input i1;
  wire i1;
  (* src = "/home/harsh-shah/week1/Day5/comp_case.v:1.45-1.47" *)
  input i2;
  wire i2;
  (* src = "/home/harsh-shah/week1/Day5/comp_case.v:1.61-1.64" *)
  input [1:0] sel;
  wire [1:0] sel;
  (* src = "/home/harsh-shah/week1/Day5/comp_case.v:1.77-1.78" *)
  output y;
  wire y;
  wire \$abc$110$new_n10 ;
  wire \$abc$110$new_n11 ;
  wire \$abc$110$new_n12 ;
  wire \$abc$110$new_n7 ;
  wire \$abc$110$new_n8 ;
  wire \$abc$110$new_n9 ;
  (* src = "/home/harsh-shah/week1/Day5/comp_case.v:1.25-1.27" *)
  wire \$abc$118$i0 ;
  (* src = "/home/harsh-shah/week1/Day5/comp_case.v:1.35-1.37" *)
  wire \$abc$118$i1 ;
  (* src = "/home/harsh-shah/week1/Day5/comp_case.v:1.45-1.47" *)
  wire \$abc$118$i2 ;
  wire \$abc$118$new_n7 ;
  wire \$abc$118$new_n8 ;
  (* src = "/home/harsh-shah/week1/Day5/comp_case.v:1.61-1.64" *)
  wire \$abc$118$sel[0] ;
  (* src = "/home/harsh-shah/week1/Day5/comp_case.v:1.61-1.64" *)
  wire \$abc$118$sel[1] ;
  (* src = "/home/harsh-shah/week1/Day5/comp_case.v:1.77-1.78" *)
  wire \$abc$118$y ;
  sky130_fd_sc_hd__mux2i_1 \$abc$118$auto$blifparse.cc:397:parse_blif$119  (
    .A0(\$abc$118$i0 ),
    .A1(\$abc$118$i1 ),
    .S(\$abc$118$sel[0] ),
    .Y(\$abc$118$new_n7 )
  );
  sky130_fd_sc_hd__nand2_1 \$abc$118$auto$blifparse.cc:397:parse_blif$120  (
    .A(\$abc$118$sel[1] ),
    .B(\$abc$118$i2 ),
    .Y(\$abc$118$new_n8 )
  );
  sky130_fd_sc_hd__o21ai_0 \$abc$118$auto$blifparse.cc:397:parse_blif$121  (
    .A1(\$abc$118$sel[1] ),
    .A2(\$abc$118$new_n7 ),
    .B1(\$abc$118$new_n8 ),
    .Y(\$abc$118$y )
  );
  assign \$abc$118$sel[1]  = sel[1];
  assign \$abc$118$sel[0]  = sel[0];
  assign \$abc$118$i1  = i1;
  assign \$abc$118$i0  = i0;
  assign \$abc$118$i2  = i2;
  assign y = \$abc$118$y ;
endmodule
