/* Generated by Yosys 0.57+157 (git sha1 b9dc57841, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/harsh-shah/week1/Day5/incomp_if2.v:1.1-8.10" *)
module incomp_if2(i0, i1, i2, i3, y);
  (* src = "/home/harsh-shah/week1/Day5/incomp_if2.v:1.26-1.28" *)
  input i0;
  wire i0;
  (* src = "/home/harsh-shah/week1/Day5/incomp_if2.v:1.36-1.38" *)
  input i1;
  wire i1;
  (* src = "/home/harsh-shah/week1/Day5/incomp_if2.v:1.46-1.48" *)
  input i2;
  wire i2;
  (* src = "/home/harsh-shah/week1/Day5/incomp_if2.v:1.56-1.58" *)
  input i3;
  wire i3;
  (* src = "/home/harsh-shah/week1/Day5/incomp_if2.v:1.71-1.72" *)
  output y;
  reg y;
  (* src = "/home/harsh-shah/week1/Day5/incomp_if2.v:2.1-7.4" *)
  wire \$0\y[0:0] ;
  wire \$abc$202$auto$rtlil.cc:3132:ReduceOr$116 ;
  (* src = "/home/harsh-shah/week1/Day5/incomp_if2.v:2.1-7.4" *)
  wire \$abc$205$0\y[0:0] ;
  wire \$abc$205$abc$202$auto$rtlil.cc:3132:ReduceOr$116 ;
  (* src = "/home/harsh-shah/week1/Day5/incomp_if2.v:1.26-1.28" *)
  wire \$abc$205$i0 ;
  (* src = "/home/harsh-shah/week1/Day5/incomp_if2.v:1.36-1.38" *)
  wire \$abc$205$i1 ;
  (* src = "/home/harsh-shah/week1/Day5/incomp_if2.v:1.46-1.48" *)
  wire \$abc$205$i2 ;
  (* src = "/home/harsh-shah/week1/Day5/incomp_if2.v:1.56-1.58" *)
  wire \$abc$205$i3 ;
  sky130_fd_sc_hd__mux2_1 \$abc$205$auto$blifparse.cc:397:parse_blif$206  (
    .A0(\$abc$205$i3 ),
    .A1(\$abc$205$i1 ),
    .S(\$abc$205$i0 ),
    .X(\$abc$205$0\y[0:0] )
  );
  sky130_fd_sc_hd__nor2_1 \$abc$205$auto$blifparse.cc:397:parse_blif$207  (
    .A(\$abc$205$i0 ),
    .B(\$abc$205$i2 ),
    .Y(\$abc$205$abc$202$auto$rtlil.cc:3132:ReduceOr$116 )
  );
  (* src = "/home/harsh-shah/week1/Day5/incomp_if2.v:2.1-7.4" *)
  always @*
    if (!\$abc$202$auto$rtlil.cc:3132:ReduceOr$116 ) y = \$0\y[0:0] ;
  assign \$abc$205$i3  = i3;
  assign \$abc$205$i1  = i1;
  assign \$abc$205$i0  = i0;
  assign \$0\y[0:0]  = \$abc$205$0\y[0:0] ;
  assign \$abc$205$i2  = i2;
  assign \$abc$202$auto$rtlil.cc:3132:ReduceOr$116  = \$abc$205$abc$202$auto$rtlil.cc:3132:ReduceOr$116 ;
endmodule
