/* Generated by Yosys 0.57+157 (git sha1 b9dc57841, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/harsh-shah/week1/Day5/incomp_if.v:1.1-6.10" *)
module incomp_if(i0, i1, i2, y);
  (* src = "/home/harsh-shah/week1/Day5/incomp_if.v:1.25-1.27" *)
  input i0;
  wire i0;
  (* src = "/home/harsh-shah/week1/Day5/incomp_if.v:1.35-1.37" *)
  input i1;
  wire i1;
  (* src = "/home/harsh-shah/week1/Day5/incomp_if.v:1.45-1.47" *)
  input i2;
  wire i2;
  (* src = "/home/harsh-shah/week1/Day5/incomp_if.v:1.60-1.61" *)
  output y;
  reg y;
  (* src = "/home/harsh-shah/week1/Day5/incomp_if.v:2.1-5.4" *)
  always @*
    if (i0) y = i1;
endmodule
