/* Generated by Yosys 0.57+157 (git sha1 b9dc57841, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* src = "sub_module.v:2.1-15.10" *)
module sub_module(a, b, out1, out2);
  (* src = "sub_module.v:3.14-3.15" *)
  input a;
  wire a;
  (* src = "sub_module.v:4.14-4.15" *)
  input b;
  wire b;
  (* src = "sub_module.v:5.15-5.19" *)
  output out1;
  wire out1;
  (* src = "sub_module.v:6.15-6.19" *)
  output out2;
  wire out2;
  assign out1 = a &(* src = "sub_module.v:10.17-10.22" *)  b;
  assign out2 = a |(* src = "sub_module.v:13.17-13.22" *)  b;
endmodule

(* top =  1  *)
(* src = "top_module.v:2.1-35.10" *)
module top_module(a, b, c, d, out_and, out_or);
  (* src = "top_module.v:3.14-3.15" *)
  input a;
  wire a;
  (* src = "top_module.v:4.14-4.15" *)
  input b;
  wire b;
  (* src = "top_module.v:5.14-5.15" *)
  input c;
  wire c;
  (* src = "top_module.v:6.14-6.15" *)
  input d;
  wire d;
  (* src = "top_module.v:7.15-7.22" *)
  output out_and;
  wire out_and;
  (* src = "top_module.v:8.15-8.21" *)
  output out_or;
  wire out_or;
  (* src = "top_module.v:11.8-11.12" *)
  wire net1;
  (* src = "top_module.v:11.14-11.18" *)
  wire net2;
  (* src = "top_module.v:12.8-12.12" *)
  wire net3;
  (* src = "top_module.v:12.14-12.18" *)
  wire net4;
  assign out_and = net1 &(* src = "top_module.v:32.20-32.31" *)  net3;
  assign out_or = net2 |(* src = "top_module.v:33.20-33.31" *)  net4;
  (* module_not_derived = 32'd1 *)
  (* src = "top_module.v:15.14-20.4" *)
  sub_module instance1 (
    .a(a),
    .b(b),
    .out1(net1),
    .out2(net2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_module.v:24.14-29.4" *)
  sub_module instance2 (
    .a(a),
    .b(b),
    .out1(net3),
    .out2(net4)
  );
endmodule
